services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: cosmos-backend
    working_dir: "/backend"
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    command: dotnet run
    volumes:
      - ./backend:/backend

  db:
    image: mariadb:11.8.2
    container_name: cosmos-database
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
