services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: cosmos-backend
    working_dir: "/backend"
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    command: dotnet run
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    profiles:
      - backend

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    container_name: cosmos-frontend
    working_dir: "/frontend"
    env_file:
      - ./frontend/.env
    ports:
      - "${VITE_FRONTEND_PORT}:${VITE_FRONTEND_PORT}"
    restart: always
    command: npm run dev
    volumes:
      - ./frontend:/frontend
    profiles:
      - frontend 

  db:
    image: mariadb:11.8.2
    container_name: cosmos-database
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    volumes:
      - db-data:/var/lib/mysql
    profiles:
      - db

volumes:
  db-data:
